name: Build

on:
  push:
    paths-ignore:
      - 'LICENCE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - id: build
        run: echo "::set-output name=RESULT::$(nix-build)"
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: ${{ steps.build.outputs.RESULT }}
          retention-ays: 1
      - name: Trigger a deploy
        run: curl ${{ secrets.CF_DEPLOY_HOOK_URL }}
