name: Deploy

on:
  push:
    paths-ignore:
      - 'LICENCE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - run: sudo apt-get install skopeo
      - run: |
          $(nix-build) | \
          gzip --fast | \
          skopeo --insecure-policy --debug --dest-creds x:${{ secrets.FLY_API_TOKEN }} --format v2s2 \
            copy \
            docker-archive:/dev/stdin \
            docker://registry.fly.io/www-kazlauskas-me:${{ github.sha }}
      - uses: superfly/flyctl-actions@1.1
        with:
          args: deploy -i registry.fly.io/www-kazlauskas-me:${{ github.sha }} --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
